### ISSUE TITLE
Create 5.12 branch

### ISSUE THREAD

**Issue by eszlari** [flathub/io.qt.qtwebkit.BaseApp#8]
When https://github.com/flathub/buildbot-config/pull/51 is merged and the runtime is built, create a 5.12 branch.

**Comment by eszlari** [comment]
@barthalion 5.12 is now available.

**Comment by aleixpol** [comment]
It's not available in flathub, no?

**Comment by aleixpol** [comment]
It needs adding here https://github.com/flathub/buildbot-config/blob/master/builds.json

**Comment by eszlari** [comment]
@barthalion Why did you add two new branches `branch/5.11` and `branch/5.12`, and not simply one called `5.12`? Where these typos?

**Comment by barthalion** [comment]
@eszlari No, they weren't, that's how we're handling multiple branches now. This is a fallback behavior for repositories not defined in builds.json though, which is why @aleixpol's pull request wasn't merged as it wouldn't trigger a new build.

I have found some time to un-hardcode qtwebkit from builds.json today so both 5.11 and 5.12 are building now.
